// Generated by Tools/product_identity.py; edit ProductIdentity.json, then --generate.
import Foundation

public enum ProductIdentity {
  public static let version = "0.1.1"
  public static let channel = "alpha"
  public static let appBuild = "191"
  public static let driverBuild = "194"
  public static let display = "rewindDV 0.1.1 (Alpha)"

  public static func matchesHost(_ info: [String: Any]) -> Bool {
    info["CFBundleShortVersionString"] as? String == version &&
      info["CFBundleVersion"] as? String == appBuild &&
      info["RewindDVProductVersion"] as? String == version &&
      info["RewindDVReleaseChannel"] as? String == channel &&
      info["RewindDVRequiredDriverBuild"] as? String == driverBuild
  }
}
