#!/usr/bin/env python3
"""Offline product identity generation and read-only release validation.

ProductIdentity.json is the authority. Generated files are committed for portable
Xcode/SwiftPM builds; builds only check them, never update source or counters.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import plistlib
import re
import sys
sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[2]
CONFIG = Path('Foundation/Config')


def version(value):
    if not isinstance(value, str) or not re.fullmatch(r'(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)', value):
        raise ValueError('Product version requires three canonical decimal integers')
    parts = tuple(map(int, value.split('.')))
    if any(n > 9999 for n in parts):
        raise ValueError('Product version component exceeds supported range')
    return parts


def build(value):
    if type(value) is not int or not 1 <= value <= 9999:
        raise ValueError('Build must be an integer from 1 through 9999 (Apple bundle representation)')
    return value


def validate(identity, history):
    if set(identity) != {'product_version', 'channel', 'app_build', 'driver_build'}:
        raise ValueError('Unexpected identity fields')
    current = version(identity['product_version'])
    if identity['channel'] != 'alpha':
        raise ValueError('This product is alpha; channel promotion requires a policy change')
    for key in ('app_build', 'driver_build'):
        build(identity[key])
        if identity[key] <= max(build(row[key]) for row in history):
            raise ValueError(key + ' is duplicated, reserved, or a downgrade')
    if current <= max(version(row['product_version']) for row in history):
        raise ValueError('Product version must advance beyond prior distributed/reserved versions')
    return identity


def load(root=ROOT):
    identity = json.loads((root / CONFIG / 'ProductIdentity.json').read_text())
    history = json.loads((root / CONFIG / 'IdentityHistory.json').read_text())['prior_identities']
    return validate(identity, history)


def generated(identity):
    v, a, d = identity['product_version'], identity['app_build'], identity['driver_build']
    banner = '// Generated by Tools/product_identity.py; edit ProductIdentity.json, then --generate.\n'
    return {
        CONFIG / 'ProductIdentity.xcconfig': banner + f'REWINDDV_PRODUCT_VERSION = {v}\nREWINDDV_RELEASE_CHANNEL = alpha\nREWINDDV_APP_BUILD = {a}\nREWINDDV_DRIVER_BUILD = {d}\nMARKETING_VERSION = $(REWINDDV_PRODUCT_VERSION)\n',
        CONFIG / 'AppBuild.xcconfig': banner + '#include "ProductIdentity.xcconfig"\nCURRENT_PROJECT_VERSION = $(REWINDDV_APP_BUILD)\n',
        CONFIG / 'DriverBuild.xcconfig': banner + '#include "ProductIdentity.xcconfig"\nCURRENT_PROJECT_VERSION = $(REWINDDV_DRIVER_BUILD)\n',
        CONFIG / 'AlphaVersion.txt': v + '\n',
        CONFIG / 'ProductIdentity.hpp': banner + f'#pragma once\n#define REWINDDV_PRODUCT_VERSION_STRING "{v}"\n#define REWINDDV_EXPECTED_DRIVER_BUILD {d}\n',
        Path('Foundation/Sources/RewindDVMonitorCore/ProductIdentity.swift'): banner + f'''import Foundation

public enum ProductIdentity {{
  public static let version = "{v}"
  public static let channel = "alpha"
  public static let appBuild = "{a}"
  public static let driverBuild = "{d}"
  public static let display = "rewindDV {v} (Alpha)"

  public static func matchesHost(_ info: [String: Any]) -> Bool {{
    info["CFBundleShortVersionString"] as? String == version &&
      info["CFBundleVersion"] as? String == appBuild &&
      info["RewindDVProductVersion"] as? String == version &&
      info["RewindDVReleaseChannel"] as? String == channel &&
      info["RewindDVRequiredDriverBuild"] as? String == driverBuild
  }}
}}
''',
    }


def check(root=ROOT):
    identity = load(root)
    for path, content in generated(identity).items():
        if not (root / path).exists() or (root / path).read_text() != content:
            raise ValueError('Generated identity drift: ' + str(path))
    # Prevent reintroduction of target/project literals that override xcconfig.
    project = (root / 'Foundation/RewindDV.xcodeproj/project.pbxproj').read_text()
    if re.search(r'"(?:MARKETING_VERSION|CURRENT_PROJECT_VERSION|REWINDDV_PRODUCT_VERSION|REWINDDV_RELEASE_CHANNEL|REWINDDV_APP_BUILD|REWINDDV_DRIVER_BUILD)"\s*=', project):
        raise ValueError('Xcode identity overrides the canonical target configuration')
    objects = dict(re.findall(r'^    "([A-Za-z0-9]+)" = \{(.*?)^    \};', project, re.M | re.S))
    for component, bundle in [('App', 'net.rewinddigital.RewindDV'), ('Driver', 'net.rewinddigital.RewindDV.Driver')]:
        refs = [key for key, body in objects.items() if '"isa" = "PBXFileReference";' in body and f'"path" = "Config/{component}Build.xcconfig";' in body]
        if len(refs) != 1:
            raise ValueError(component + ' canonical configuration reference missing')
        configs = [body for body in objects.values() if '"isa" = "XCBuildConfiguration";' in body and f'"PRODUCT_BUNDLE_IDENTIFIER" = "{bundle}";' in body]
        if len(configs) != 2 or any(f'"baseConfigurationReference" = "{refs[0]}";' not in body for body in configs):
            raise ValueError(component + ' Debug/Release must use canonical target configuration')
        if sorted(re.search(r'"name" = "([^\"]+)";', body)[1] for body in configs) != ['Debug', 'Release']:
            raise ValueError(component + ' configuration inventory drift')
    return identity


def bundle_identity(app, identity):
    driver = app / 'Contents/Library/SystemExtensions/net.rewinddigital.RewindDV.Driver.dext'
    a = plistlib.loads((app / 'Contents/Info.plist').read_bytes())
    d = plistlib.loads((driver / 'Info.plist').read_bytes())
    expected = {'CFBundleShortVersionString': identity['product_version']}
    for info, component, identifier in [(a, 'app', 'net.rewinddigital.RewindDV'), (d, 'driver', 'net.rewinddigital.RewindDV.Driver')]:
        for key, value in {**expected, 'CFBundleVersion': str(identity[component + '_build']), 'CFBundleIdentifier': identifier}.items():
            if info.get(key) != value:
                raise ValueError(component + ' bundle disagrees with source: ' + key)
    for key, value in {'RewindDVAlphaVersion': identity['product_version'], 'RewindDVProductVersion': identity['product_version'], 'RewindDVReleaseChannel': identity['channel'], 'RewindDVRequiredDriverBuild': str(identity['driver_build'])}.items():
        if a.get(key) != value:
            raise ValueError('App metadata disagrees with source: ' + key)
    if d.get('IOKitPersonalities', {}).get('RewindDVFoundationController', {}).get('FoundationBuildNumber') != str(identity['driver_build']):
        raise ValueError('Driver registry marker disagrees with bundle build')
    hashes = {'app': hashlib.sha256((app / 'Contents/MacOS/RewindDV').read_bytes()).hexdigest(), 'driver': hashlib.sha256((driver / 'net.rewinddigital.RewindDV.Driver').read_bytes()).hexdigest()}
    return {'identity': identity, 'executables_sha256': hashes, 'package_name': f"rewindDV-{identity['channel']}-{identity['product_version']}-App{identity['app_build']}-Driver{identity['driver_build']}.zip"}


def compare_artifacts(previous, candidate):
    for component in ('app', 'driver'):
        key = component + '_build'
        if previous['identity'][key] == candidate['identity'][key] and previous['executables_sha256'][component] != candidate['executables_sha256'][component]:
            raise ValueError('Same-identity/different-artifact ambiguity: ' + component)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--generate', action='store_true', help='Explicit reviewed source update; never invoked during builds')
    p.add_argument('--check', action='store_true', help='Read-only drift check (default)')
    p.add_argument('--app-plist', type=Path, help='Write derived build output only')
    p.add_argument('--bundle', type=Path, help='Validate actual full app and embedded DEXT')
    p.add_argument('--tag', help='Validate proposed channel tag; never create it')
    p.add_argument('--previous-manifest', type=Path, help='Reject same component build with changed executable hash')
    args = p.parse_args()
    if args.generate:
        for path, content in generated(load()).items():
            (ROOT / path).write_text(content)
    identity = check()
    if args.tag and args.tag != identity['channel'] + '-' + identity['product_version']:
        raise ValueError('Tag disagrees with canonical product identity')
    if args.app_plist:
        output = args.app_plist.resolve()
        if output.is_relative_to(ROOT):
            raise ValueError('Build output must be outside source')
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_bytes(plistlib.dumps({'RewindDVAlphaVersion': identity['product_version'], 'RewindDVProductVersion': identity['product_version'], 'RewindDVReleaseChannel': identity['channel'], 'RewindDVRequiredDriverBuild': str(identity['driver_build']), 'RewindDVCandidateRevision': 'Native ' + os.environ.get('CONFIGURATION', 'development') + ' source candidate; hardware qualification pending'}))
    if args.previous_manifest and not args.bundle:
        raise ValueError('--previous-manifest requires --bundle')
    result = bundle_identity(args.bundle, identity) if args.bundle else identity
    if args.previous_manifest:
        compare_artifacts(json.loads(args.previous_manifest.read_text()), result)
    print(json.dumps(result, sort_keys=True))


if __name__ == '__main__':
    try:
        main()
    except (ValueError, OSError, KeyError) as error:
        sys.exit(str(error))
